# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  nixos-hardware = builtins.fetchGit {
    url = "https://github.com/NixOS/nixos-hardware.git";
    ref = "master";
  };
in {
  imports = [
    (import "${nixos-hardware}/framework/13-inch/7040-amd")
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "thunderbolt" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [
    # NB: Disabled due to conflict with Virtualbox.
    # "kvm-amd"
    # Virtual Microphone, built-in
    "snd-aloop"
    # Virtual Camera
    "v4l2loopback"
  ];
  boot.kernelParams = [ "mem_sleep_default=deep" ];
  boot.extraModprobeConfig = ''
    options v4l2loopback exclusive_caps=1 card_label="Virtual Camera"
  '';
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback.out
  ];

  boot.supportedFilesystems = [ "ntfs" ];

  # luks
  boot.initrd.luks.devices = {
    crypted = {
      device = "/dev/disk/by-uuid/00d997b7-5c29-4ab5-bca5-9a7a349cf6d8";
      preLVM = true;
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f06ba414-6b90-4013-bbda-d4c4c3b0c599";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/463F-00A4";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/38bff18d-e955-49de-8e06-296c8d480a50"; }];

  # Configure sleep + hibernate.
  # https://www.worldofbs.com/nixos-framework/
  boot.resumeDevice = "/dev/disk/by-uuid/38bff18d-e955-49de-8e06-296c8d480a50";

  networking.useDHCP = lib.mkDefault true;

  services.fwupd.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
